name: ZAP API Scan

on:
  push:
    branches: [ "dev", "staging",  ]
  workflow_dispatch:
    
jobs:
  security-scan:
    runs-on: "th878"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up "x-api-key" as an environment variable
        run: |
          echo "x-api-key=${{ secrets.X_API_KEY }}" >> $GITHUB_ENV
          
      - name: Perform ZAP API scan
        uses: zaproxy/action-api-scan@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          format: openapi
          target: 'https://ctx-api-stg.ccte.epa.gov/docs/exposure.json'
          cmd_options: '-a'
        env:
          ZAP_AUTH_HEADER_VALUE: "x-api-key=${{ secrets.X_API_KEY }}"
